services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "pw"

connect:
  image: postgres
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "create database y;"
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "create database y2;"

python_2_7_tests:
  image: python:2.7
  script:
    # manually install ase deps
    - pip install numpy scipy matplotlib flask psycopg2
    # extra packages for testing
    - pip install pyflakes netCDF4
    # using "install from source" instructions
    - export PATH=$PATH:$CI_PROJECT_DIR/bin
    - echo $PATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH
    # tests
    - python --version
    - ase info
    - ase test
    # pyflakes code check (Python 2 version)
    - cd $CI_PROJECT_DIR
    - python ase/test/__init__.py

python_3_tests:
  image: python:3
  script:
    # manually install extra deps
    - pip install netCDF4 pyflakes psycopg2
    # 'pip install' pulls in all required packages
    - pip install .
    # Run tests
    - python --version
    - ase info
    - ase test
    # pyflakes code check (Python 3 version)
    - cd $CI_PROJECT_DIR
    - python ase/test/__init__.py

conda_tests:
   image: continuumio/anaconda3
   script:
     # manually install extra deps
     - apt-get install -yq libgl1-mesa-glx
     - conda install -yq pip wheel numpy scipy pyflakes matplotlib flask psycopg2
     # 'pip install' pulls in all required packages
     - pip install .
     # Run tests
     - python --version
     - ase info
     - ase test

docs_test:
  image: python:3
  script:
    # 'pip install' pulls in all required packages (include docs)
    - pip install .[docs]
    # build the docs
    - ase info
    - which sphinx-build
    - cd $CI_PROJECT_DIR/doc
    - sphinx-build -W . build

