master:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy
    - pwd
    - echo $HOME
    - echo $USER
    - echo $PYTHONPATH
    - PATH=$PATH:/builds/$USER/ase/tools PYTHONPATH=$PYTHONPATH:/builds/ase/ase python setup.py test
