services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"

python_2_7_tests:
  image: python:2.7
  script:
    - pip install numpy scipy matplotlib flask psycopg2-binary
    - pip install netCDF4
    # using "install from source" instructions
    - export PATH=$PATH:$CI_PROJECT_DIR/bin
    - echo $PATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH
    - python --version
    - ase test

# Check oldest supported Python with oldest supported libraries.
# Does not install any optional libraries except matplotlib.
python_3_oldlibs_tests:
  image: python:3.4-slim
  script:
    - pip install numpy==1.9.0 scipy==0.14.0 matplotlib==2.0.0
    - pip install --no-deps .
    - python --version
    - ase test

# Check newest Python with all the standard dependencies at newest versions.
python_3_tests:
  image: python:3-slim
  script:
    - pip install pyflakes psycopg2-binary
    - pip install .
    - python --version
    - ase test
    - cd $CI_PROJECT_DIR
    - pyflakes ase doc

conda_tests:
   image: continuumio/anaconda3
   script:
     - apt-get install -yq libgl1-mesa-glx
     - conda install -yq pip wheel numpy scipy pyflakes matplotlib flask
     - pip install .
     - python --version
     - ase test

docs_test:
  image: python:3
  script:
    - pip install .[docs]
    - ase info
    - which sphinx-build
    - cd $CI_PROJECT_DIR/doc
    - sphinx-build -W . build
