master:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy python-scipy pyflakes
    - pwd
    - echo $HOME
    - echo $PWD
    - echo $PYTHONPATH
    - PATH=$PATH:$PWD/tools PYTHONPATH=$PYTHONPATH:$PWD python setup.py test
    - pyflakes3 ase doc | grep -v -E "jacapo|tasks|execute.py
